model_config:
  model: InceptionV3 #ResNet50, InceptionV3, DenseNet121
  initial_filter_size: [64]
  kernel: [3]
  drop_out_rate: [0.2]
  input_size: [800, 800] #h, w
  channel: 1
  num_class: 2
  attention: False 
train_config:
  loss: w_ce
  accuracy: dice_score
  optimizer: Adam
  lr_rate: [0.01]
  weight_decay: [0.0001]
  batch_size: [16]
  epochs: 200
  num_workers: 20
  use_cuda: True
  seed: 35
dataset_config:
  train_path: '/kuacc/users/ocaki13/hpc_run/ultrasoundClassification/fold1/train'
  val_path: '/kuacc/users/ocaki13/hpc_run/ultrasoundClassification/fold1/val'
  test_path: '/kuacc/users/ocaki13/hpc_run/ultrasoundClassification/fold1/test'
  aug_rate: [0]
  save_dir: classifierExp1Sgd_incept
  class_names: ['normal','anormal']
resume:
  flag: False
  path: exp3/models/last_epoch.pt
  epoch: 10

