model_config:
  model: ResNet50 #ResNet50, InceptionV3, DenseNet121
  initial_filter_size: [32]
  kernel: [3]
  dropout_rate: [0.5]
  input_size: [400, 640] #h, w
  channel: 1
  num_class: 2
  attention: False 
train_config:
  loss: w_ce
  accuracy: dice_score
  optimizer: Adam
  lr_rate: [0.0005]
  weight_decay: [0.0001]
  batch_size: [4]
  epochs: 200
  num_workers: 20
  use_cuda: True
  seed: 288
dataset_config:
  train_path: '../3folddatasett_copy/fold1/train/'
  val_path: '../3folddatasett_copy/fold1/val/'
  test_path: '../3folddatasett_copy/fold1/test/'
  augmentation: False
  aug_rate: [0]
  save_dir: results
  class_names: ['control','RD']
resume:
  flag: False
  path: exp3/models/last_epoch.pt
  epoch: 10

